[workspace]
resolver = "2"
members = [
    "foxtive-ntex",
    "foxtive-ntex-multipart"
]

[workspace.dependencies]
thiserror = { version = "2.0.12" }
ntex = { version = "2.12.2", default-features = false, features = ["tokio"] }
