[package]
name = "foxtive-ntex"
version = "0.2.1"
edition = "2021"
license = "MIT"
description = "Micro-Framework Based on Ntex"
repository = "https://github.com/foxtive/foxtive-ntex"
authors = ["ahmard"]

[features]
strum = ["dep:strum"]
static = ["dep:ntex-files"]
validator = ["dep:validator"]
database = ["foxtive/database"]
rabbitmq = ["foxtive/rabbitmq"]
redis = ["foxtive/redis"]
base64 = ["foxtive/base64"]
hmac = ["foxtive/hmac"]
reqwest = ["foxtive/reqwest"]
crypto = ["foxtive/crypto"]
jwt = ["foxtive/jwt"]
regex = ["foxtive/regex"]
templating = ["foxtive/tera"]
multipart = ["foxtive-ntex-multipart"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "2.0.12"
log = { version = "0.4.26" }
uuid = { version = "1.15.1", features = ["v4", "serde"] }
serde = { version = "1.0.218", features = ["derive"] }
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros", "time"] }
chrono = { version = "0.4.40", features = ["serde"] }
serde_json = { version = "1.0.140", features = ["raw_value"] }
futures-util = { version = "0.3.31" }
ntex = { version = "2.11.0", features = ["tokio"] }
ntex-files = { version = "2.0.0", optional = true }
ntex-cors = { version = "2.0.0" }
validator = { version = "0.20.0", features = ["derive"], optional = true }
strum = { version = "0.27.1", default-features = false, features = ["std"], optional = true }

foxtive = { version = "0.5.1" }
foxtive-ntex-multipart = { version = "0.1.0", optional = true }
