name: Code QA & Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  detect-changes:
    name: Detect Changed Crates
    runs-on: ubuntu-latest

    outputs:
      changed_crates: ${{ steps.detect-changes.outputs.changed_crates }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history

      - name: Detect changed crates
        id: detect-changes
        run: |
          if git rev-parse HEAD~1 > /dev/null 2>&1; then
            CHANGED_CRATES=$(git diff --name-only HEAD~1..HEAD | grep -E '^[^/]+/' | cut -d '/' -f 1 | sort | uniq)
          else
            CHANGED_CRATES=$(find . -maxdepth 1 -type d -not -path './.*' -not -path '.' | cut -d '/' -f 2 | sort | uniq)
          fi

          VALID_CRATES=""
          for CRATE in $CHANGED_CRATES; do
            if [[ "$CRATE" == *"foxtive"* ]] && [ -f "$CRATE/Cargo.toml" ]; then
              VALID_CRATES="$VALID_CRATES $CRATE"
            fi
          done

          echo "Changed crates: $VALID_CRATES"
          echo "::set-output name=changed_crates::$VALID_CRATES"

  test-code:
    name: Test Codebase
    runs-on: ubuntu-latest
    needs: detect-changes

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Run Clippy and Tests on changed crates
        run: |
          CHANGED_CRATES="${{ needs.detect-changes.outputs.changed_crates }}"
          if [ -z "$CHANGED_CRATES" ]; then
            echo "No crates changed."
            exit 0
          fi

          for CRATE in $CHANGED_CRATES; do
            echo "Running Clippy and Tests for crate: $CRATE"
            cargo clippy --package $CRATE --all-features
            cargo test --package $CRATE --all-features
          done

  release:
    name: Release Package
    runs-on: ubuntu-latest
    needs: [detect-changes, test-code]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    outputs:
      published_crates: ${{ steps.publish.outputs.published_crates }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for tag creation

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Publish changed crates
        id: publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          CHANGED_CRATES="${{ needs.detect-changes.outputs.changed_crates }}"
          if [ -z "$CHANGED_CRATES" ]; then
            echo "No crates changed. Skipping release."
            exit 0
          fi

          PUBLISHED_CRATES=""
          for CRATE in $CHANGED_CRATES; do
            echo "Publishing $CRATE..."
            cargo publish -p $CRATE && PUBLISHED_CRATES="$PUBLISHED_CRATES $CRATE"
          done

          echo "::set-output name=published_crates::$PUBLISHED_CRATES"

  tag-version:
    name: Tag Version
    runs-on: ubuntu-latest
    needs: release
    permissions:
      contents: write
    if: needs.release.outputs.published_crates != ''

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for tag creation

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Create and push Git tag for released crates
        run: |
          PUBLISHED_CRATES="${{ needs.release.outputs.published_crates }}"
          for CRATE in $PUBLISHED_CRATES; do
            VERSION=$(grep '^version' "$CRATE/Cargo.toml" | sed -E 's/version\s*=\s*"([^"]+)"/\1/')

            if [ -z "$VERSION" ]; then
              echo "Could not extract version for $CRATE"
              continue
            fi

            git config --global user.name "GitHub Action"
            git config --global user.email "action@github.com"

            TAG="$CRATE-$VERSION"
            echo "Checking if tag $TAG exists..."
            if git rev-parse "$TAG" >/dev/null 2>&1; then
              echo "Tag $TAG already exists. Skipping..."
            else
              echo "Creating new tag $TAG for $CRATE..."
              git tag -a "$TAG" -m "Release $TAG"
              git push origin "$TAG"
            fi
          done

  lint-code:
    name: Lint Codebase
    runs-on: ubuntu-latest
    needs: [detect-changes, test-code, release, tag-version]
    permissions:
      contents: write
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run cargo fmt
        run: cargo fmt --all

      - name: Commit fmt changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "style(cargo-fmt): apply changes" || echo "No changes to commit"

      - name: Push fmt changes
        run: git push origin HEAD:${{ github.ref }}
